### ISSUE TITLE
Comments Preview

### ISSUE THREAD

**Issue by wireddown** [wireddown/ghpages-ghcomments#15]
This is the comment thread for the [preview page](http://downtothewire.io/ghpages-ghcomments/preview/comments/) of on-page comments (Issue #11).

**Comment by wireddown** [comment]
*First* comment ;-)

**Comment by naveenshaji** [comment]
### Nice :-)

**Comment by wireddown** [comment]
Here is a demo.

**Comment by wireddown** [comment]
Now with better latent connection support.

**Comment by wireddown** [comment]
Now supporting GitHub OAuth [web-application flow](https://developer.github.com/v3/oauth/#web-application-flow) authorization.

**Comment by naveenshaji** [comment]
Testing GitHub OAuth web-application flow authorization.

**Comment by wireddown** [comment]
Now with better feedback for:

* latent connections
* revoked authorization.

**Comment by naveenshaji** [comment]
Testing again

**Comment by wireddown** [comment]
This has been released -- http://downtothewire.io/ghpages-ghcomments/setup/
