### ISSUE TITLE
No error message displayed if entered OAuth token is longer than 40 characters

### ISSUE THREAD

**Issue by naveenshaji** [wireddown/ghpages-ghcomments#16]
![gif demonstrating bug](https://cloud.githubusercontent.com/assets/10815281/6488324/c7b64d92-c2bc-11e4-878c-dfac9e2a17c7.gif)
As you can see on the gif here, no error message displayed if entered OAuth token is longer than 40 characters. I have entered a string of 42 characters and this leads to an awkward situation if the user does not know what went wrong. @wireddown Please see If you can fix this.

**Comment by wireddown** [comment]
Yes, this won't be a problem :-)

**Comment by wireddown** [comment]
The feature preview page provides an error message when the token's length is anything other than 40 or 0:

http://downtothewire.io/ghpages-ghcomments/preview/comments/
