### ISSUE TITLE
How do I remove git hooks?

### ISSUE THREAD

**Issue by getsetbro** [wireddown/ghpages-ghcomments#19]
As instructed here: http://downtothewire.io/ghpages-ghcomments/advanced/uninstall/

**Comment by wireddown** [comment]
When you open `.git/hooks/pre-commit` and `.git/hooks/pre-push` in a text editor, is it still unclear what you should do?

**Comment by getsetbro** [comment]
I was able to see and find them once I turned on showing of hidden files. Thanks

**Comment by wireddown** [comment]
Ok, would it be helpful to mention in the uninstall instructions that the `.git` folder is hidden?

**Comment by getsetbro** [comment]
I think so.

**Comment by wireddown** [comment]
Done :-)
