### ISSUE TITLE
Login to Github button opens an example page instead

### ISSUE THREAD

**Issue by SaraSoueidan** [wireddown/ghpages-ghcomments#20]
Clicking on the Login button opens this page instead: http://downtothewire.io/ghpages-ghcomments/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=32838118351823952230

The URL bar starts with this URL:
https://github.com/login/oauth/authorize?client_id=0ef5ca17b24db4e46807&scope=public_repo&state=37146625982598589928&redirect_uri=http%3A%2F%2Fsarasoueidan.com%2Fpublic%2Fhtml%2Fgpgc_redirect%2Findex.html

but then somehow redirects automatically to the example page.

**Comment by wireddown** [comment]
Thanks for the URLs -- it appears I don't have good error handling for this situation, but they provide some clues:

* error = redirect_uri_mismatch
* error_description = The redirect_uri MUST match the registered callback URL for this application
* error_uri = https://developer.github.com/v3/oauth/#redirect-uri-mismatch

Try changing your `callback_url` in `_data/gpgc.yml` from `http://sarasoueidan.com/public/html/gpgc_redirect/index.html` (which gives me a 404) to `http://sarasoueidan.com/public/html/gpgc_redirect.html` (which gives me the redirect page).

I'm also beginning to worry that my GitHub application for ghpages-ghcomments cannot be reused for other sites. If changing the `callback_url` doesn't help, then please create a GitHub application ([Step 0 here](http://downtothewire.io/ghpages-ghcomments/advanced/custom-github-app/)) and update the `github_application:` object in `_data/gpgc.yml` to use your `client_id`.

If using your own GitHub application isn't enough, then you'll also need to create a Heroku instance so your `client_id` and `client_secret` are paired ([Step A here](http://downtothewire.io/ghpages-ghcomments/advanced/custom-github-app/)).

**Comment by wireddown** [comment]
From our [Twitter conversation](https://twitter.com/SaraSoueidan/status/647761724549013504):

* It's ok for the site repo to be private, but the comments must be associated with a public repo. This private/public configuration is possible, but not documented.
* If the repo was private while you created a new post, then the comment thread wouldn't have been created.

I can add a blog post describing this situation and how to use comments, but it will take a few days.

**Comment by wireddown** [comment]
I can confirm that my GitHub application for ghpages-ghcomments cannot be reused for other sites :-( The test user and repository [pixated/pixated.github.io](https://github.com/pixated/pixated.github.io) has the same behavior as what you describe.

I need to create/update the documentation for these two topics:

1. Setup -- update to include the creation of a GitHub Application and Heroku authenticator
1. Private Repos -- create a topic to describe how to use comments with a private repository

**Comment by wireddown** [comment]
I have updated the [Setup instructions](http://downtothewire.io/ghpages-ghcomments/setup/), and, after following them, [comments work](http://pixated.github.io/2014/01/02/introducing-lanyon/) for my test user's repository site.

I will still add a page for using comments with private repositories, but the basic outline is:

1. Keep your repository private.
1. Create a public repository for storing the comments.
1. Update `_data\config.yml` to use the public repository.

**Comment by wireddown** [comment]
I've added [a new post about using private GitHub repositories](http://downtothewire.io/ghpages-ghcomments/2015/10/03/using-ghpages-ghcomments-with-private-github-repositories/), but there isn't really anything new than what I sketched above, just some background for newer GitHub users.
