### ISSUE TITLE
Login/Redirect issues

### ISSUE THREAD

**Issue by titusfortner** [wireddown/ghpages-ghcomments#22]
1) Incognito Window, so no caching issues
2) Navigate to http://downtothewire.io/2015/08/13/exploring-the-variables-created-by-jekyll-for-liquid/
3) Click "Login to Github"
4) Enter Github credentials

The URL in that small popup window ends up:
http://downtothewire.io/ghpages-ghcomments/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=376053631819528379

I'm never actually logged in to be able to make a comment
Behavior is also present on Firefox

**Comment by wireddown** [comment]
Thanks.

The GitHub application settings for the comments on downtothewire.io were incorrect -- they were tuned for the ghpages-ghcomments project page.

**Comment by titusfortner** [comment]
Yeah, I just read the discussion on #20. I had a similar "can't log in" problem, so I thought it might be connected to this issue. After some more fiddling, I realized it is different. Also, I just found this directory which I don't see linked to anywhere on your site. - https://github.com/wireddown/ghpages-ghcomments/tree/gh-pages/advanced It's helping me understand things better. Hopefully I can figure out what step I'm missing that gets this working.

**Comment by titusfortner** [comment]
Yup, can't figure this out.

I'm not publishing the repo for the jekyll code on github, so I created [this repo](https://github.com/titusfortner/watirtight_comments/) to post comments with:  (I'm assuming the ```gpgcCreateCommentIssue.sh bootstrap``` command created [this issue]( https://github.com/titusfortner/watirtight_comments/issues/1)).

On [my blog entry page](http://www.watirtight.com/2015/08/03/welcome.html), I click the login to github button, a window pops up, has me sign in to github, then asks me to authorize the app, (the account shows it as an authorized app when I check the list), but the redirect hangs (http://www.watirtight.com/public/html/gpgc_redirect.html?code=NUMBERS&state=NUMBERS) and doesn't close the window.

When I refresh the blog page, I'm still not logged in.

I can add a comment on github and have it show up on my site, so I know they are connected.
I set up my heroku app with the "deploy to heroku" button here: https://github.com/prose/gatekeeper using https://watirtight-testing.herokuapp.com/
I'm getting the bad_code error when I test authenticating, so it should be working.

I have no idea what part I'm missing. Any thoughts? :)

**Comment by wireddown** [comment]
> Also, I just found this directory which I don't see linked to anywhere on your site. - https://github.com/wireddown/ghpages-ghcomments/tree/gh-pages/advanced

It's purposefully difficult to find, and only has a link in the sidebar; some advanced pages are linked from the main pages and blog posts. Mainly, though, it's developer documentation for folks who want add or change behavior.

> I'm not publishing the repo for the jekyll code on github, so I created [this repo](https://github.com/titusfortner/watirtight_comments/) to post comments with (I'm assuming the gpgcCreateCommentIssue.sh bootstrap command created [this issue](https://github.com/titusfortner/watirtight_comments/issues/1)).

Yes, that is what I would expect. The git hooks are working :-)

> but the redirect hangs (http://www.watirtight.com/public/html/gpgc_redirect.html?code=__NUMBERS__&state=__NUMBERS__) and doesn't close the window.

I can confirm this behavior for me, too.

Looking at the source of your Welcome page, I see that the `gpgc` variable is missing a value for its `site_url` member. This information is also used in the [redirect page](https://github.com/wireddown/ghpages-ghcomments/blob/release/public/html/gpgc_redirect.html). Without that information, the event data that the login window sends to the blog window is incomplete, and the resulting behavior is undefined and browser-dependent. Both of these values are determined by your site's `_config.yml` file, and I believe you should set yours to `http://www.watirtight.com`.

*sigh* More than half of any software component is error handling. There's still more diagnostics to add.

**Comment by titusfortner** [comment]
Awesome, thanks, I got it working! Still learning the Jekyll... :)

**Comment by wireddown** [comment]
:+1:

I know the feeling.

![bootstrapping](https://i.imgur.com/xXeU8wP.gif)
