### ISSUE TITLE
User appears to authenticate, but does not show as logged in

### ISSUE THREAD

**Issue by Jcrash29** [wireddown/ghpages-ghcomments#26]
Hi, 

Any help would be appreciated I have been looking at issues #20 and #22, but haven't yet been able to solve my problem.

The current issue I am experiencing is that when I press the "login to github" button I am able to login and authorize the use of my application (I see this in my authorized applications list). However the comments section on my site never reflects that I have been logged in and am able to post.

I have compared the your site:
http://downtothewire.io/ghpages-ghcomments/2015/01/18/the-phrenic-shrine-reveals-itself/

and my own site:
http://www.jcrash.com/biking/2015/09/06/SF_trip

The only difference I have found yet is that after authentication it shows my username on your site, but not on my own.

Any help is appreciated. Really great work you have put together, can't wait to use it on my site!

**Comment by Jcrash29** [comment]
Clicking Login to Github from my phone, opens a new tab with the following URL:

www.jcrash.com//public/html/gpgc_redirect.html?code= _NUMBERS_ &state= _NUMBERS_

This URL is similar to the one seen in #22, however I believe I have set my _config.yml correctly. Initially there was an error present on the diagnostics informing me that site_url was not set, after reading #22 and setting the url: www.jcrash.com the diagnostics error went away, but I was left with the _NUMBERS_ issue.

UPDATE: 

It appears that your downtothewire.io site does the same thing when I click the login to github site. There most simply be an issue with authenticating on an android phone (My phone)? Would you like me to create a new issue?

**Comment by wireddown** [comment]
> The current issue I am experiencing is that when I press the "login to github" button I am able to login and authorize the use of my application (I see this in my authorized applications list). However the comments section on my site never reflects that I have been logged in and am able to post.

I was able to reproduce this as well. When I logged in to GitHub from your _SF Trip_ post, the comment form still showed me as logged out, even though I saw your _Allowing comments to be pulled on website_ OAuth application listed as [authorized](https://github.com/settings/applications).

We need more information than the diagnostics currently trace. Would you make two changes to your site:
1. `public/js/gpgc_core.js`
   ![gpgc_core](https://cloud.githubusercontent.com/assets/8404598/17651586/bcc35f38-622f-11e6-914f-c65e44ab2897.png)
2. `public/html/gpgc_redirect.html`
   ![gpgc_redirect](https://cloud.githubusercontent.com/assets/8404598/17651587/d1a0dcbe-622f-11e6-8309-e21fe517c2c5.png)

This will print more information to your browser's debug console (usually accessed via F12), and it will keep the popup window open after a log in. These changes will allow you and I (and anyone else) to see some of the intermediate state.

Also, would you share the _Authorization callback URL_ for your [OAuth application](https://github.com/settings/developers)? For example, mine is:

![gpgc_auth](https://cloud.githubusercontent.com/assets/8404598/17651609/50059d10-6230-11e6-933e-68e5dc17961a.png)

**Comment by wireddown** [comment]
> It appears that your downtothewire.io site does the same thing when I click the login to github site. There most simply be an issue with authenticating on an android phone (My phone)? Would you like me to create a new issue?

Yes, please do. This misbehavior also happens for my site on my Android phone.

**Comment by Jcrash29** [comment]
Changes have been pushed to my public repo located [here](https://github.com/BananaSlug/bananaslug.github.com)

Below is my gpgc.yml file which includes my authorization callback url.

`repo_owner: bananaslug`
`repo_name: bananaslug.github.com`
`disabled: false`
`use_show_action: false`
`label_name: Post Comments`
`label_color: 666666`
`github_application:`
`client_id: da666e21462e0cf3db19`
`code_authenticator: https://jcrashcomments.herokuapp.com/authenticate/`
`callback_url: http://jcrash.com//public/html/gpgc_redirect.html`
`enable_diagnostics: true`

Note that based on the comment in #20 I have used gpgc_redirect.html, instead of gpgc_redirect/index.html.

**Comment by Jcrash29** [comment]
Looks like the issue now displays itself:

`Failed to execute 'postMessage' on 'DOMWindow': the target origin provided ('http://jcrash.com') does not match the recipient window's origin ('http://www.jcrash.com').`

My next move to consider is moving all references of "jcrash.com" to "www.jcrash.com"

I'll report back.

**Comment by Jcrash29** [comment]
That appears to have solved the problem.

![capture](https://cloud.githubusercontent.com/assets/1900567/17651979/6be7ee8c-6237-11e6-9280-72ff398f2dd7.PNG)

I'm uncertain if there is a change to be made on gpgc. Perhaps the above log messages could be added to the trouble shooting section?

Appreciate your help greatly!
