### ISSUE TITLE
The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.

### ISSUE THREAD

**Issue by AlineTalhouk** [wireddown/ghpages-ghcomments#30]
Hello, I followed the setup instructions provided in here http://downtothewire.io/ghpages-ghcomments/setup/ 

I am getting an error message. Any help would be appreciated!
Thanks

**Comment by wireddown** [comment]
I'm sorry you ran into a surprise. Would you share what you uncovered? Perhaps I can improve the error messages and handling.
