### ISSUE TITLE
onRetrieveTokenFailed after setting a custom domain

### ISSUE THREAD

**Issue by thevinter** [wireddown/ghpages-ghcomments#38]
It's me again, sorry for the trouble. After buying a new domain for my website the comments stopped working. I tried changing all the references so they'd point to the new URL but to no avail, at first it didn't want to load and now it's giving me the following error.

```
onRetrieveTokenFailed: 

{"error":"bad_code"}

```
Debugging via the console didn't help me much but my knowledge on that front is very limited.

**Comment by wireddown** [comment]
My guess is the GitHub developer application and the mini-service at `gpgc.github_application_code_authenticator_url` (see steps 1 and 2 on [setup](http://downtothewire.io/ghpages-ghcomments/setup/), more details on 2 [also available](http://downtothewire.io/ghpages-ghcomments/advanced/custom-github-app/)) also need to be updated with the new domain name, highlighted:

```diff
 function getTokenUsingCode(code) {
   getGitHubApiRequestWithCompletion(
+    gpgc.github_application_code_authenticator_url + code,
     /* data: */ null,
     /* accessToken: */ null,
     /* onPreRequest: */ noop,
     onTokenRetrieved,
     onRetrieveTokenFailed
   );
 }
```

https://github.com/wireddown/ghpages-ghcomments/blob/release/public/js/gpgc_core.js#L248
