### ISSUE TITLE
Source: https://help.github.com/articles/markdown-basics

### ISSUE THREAD

**Issue by Lindakate001** [wireddown/ghpages-ghcomments#41]
Source: https://help.github.com/articles/markdown-basics

_Originally posted by @wireddown in https://github.com/wireddown/ghpages-ghcomments/issues/5#issuecomment-70784383_

**Comment by wireddown** [comment]
@Lindakate001 -- please share some more about your issue 😄 and let me know whether there is a change you want to see.

**Comment by wireddown** [comment]
I'm closing this for now. If you have a question or message, please let me know :D
