### ISSUE TITLE
Comments in _config.yml destroy page link in issue

### ISSUE THREAD

**Issue by philippneugebauer** [wireddown/ghpages-ghcomments#9]
Just as example:

[GitHub-Pages Comments hosted on GitHub implemented](http://philippneugebauer.net # the base hostname & protocol for your site/2015/02/01/post-github-pages-comments-work).

**Comment by wireddown** [comment]
This is a symptom of #6 -- _Git hooks do not work_

**Comment by philippneugebauer** [comment]
Sure? That happened to me after I fixed the problem and started with the comments from scratch

**Comment by wireddown** [comment]
Yes.

Since the defect is "the git hooks do not fully understand yml syntax" using:
* double quotes in variables breaks the JSON that the hooks send to GitHub
* in-line comments are not removed and are incorrectly inserted into hooks' data
